name: Lint and Format

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install flake8 black
      - name: Check code formatting (black)
        run: |
          black --check .
      - name: Lint with flake8
        run: |
          flake8 --count --statistics --show-source .
